name: sui
description: Sui Dart SDK.
version: 0.1.3
homepage: https://github.com/mofalabs/sui

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bip32: 2.0.0
  bip39: 1.0.6
  ed25519_edwards: 0.3.1
  pointycastle: 3.7.3
  bcs: ^0.0.4
  dio: ^5.1.2
  hex: ^0.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

